# Generated by Django 4.2.16 on 2026-06-18 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailJSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(blank=True, max_length=100)),
                ('template_id', models.CharField(blank=True, max_length=100)),
                ('public_key', models.CharField(blank=True, max_length=100)),
                ('private_key', models.CharField(blank=True, max_length=100)),
                ('from_email', models.EmailField(blank=True, help_text='البريد الذي سيظهر كمرسل', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='الاسم الذي سيظهر كمرسل', max_length=100)),
                ('is_configured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emailjs_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدادات EmailJS',
                'verbose_name_plural': 'إعدادات EmailJS للمستخدمين',
            },
        ),
    ]
