# Generated by Django 4.2.16 on 2026-06-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailjsconfig',
            name='api_keys',
            field=models.TextField(blank=True, default='', help_text='كود QR للمصادقة'),
        ),
    ]
