# Generated by Django 4.2.16 on 2026-06-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_emaillog_click_count_emaillog_clicked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_recurring_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recurrence',
            field=models.CharField(choices=[('none', 'بدون تكرار'), ('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='none', max_length=20),
        ),
    ]
