# Generated by Django 4.2.16 on 2026-06-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_is_recurring_active_campaign_next_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ab_split_percent',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ab_test_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ab_variant',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='campaign',
            name='body_html_b',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subject_b',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
