# Generated by Django 4.2.16 on 2026-06-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='body_html_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='body_text_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='subject_snapshot',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='CampaignMessageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_steps', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['campaign', 'step_number'],
                'unique_together': {('campaign', 'step_number')},
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='message_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='campaigns.campaignmessagestep'),
        ),
    ]
