# Generated by Django 4.2.16 on 2026-07-20 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0006_emaillog_body_html_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartSendBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body_html', models.TextField(blank=True)),
                ('total', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دفعة إرسال ذكي',
            },
        ),
        migrations.CreateModel(
            name='SmartSendRecipientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaigns.smartsendbatch')),
            ],
            options={
                'unique_together': {('batch', 'email')},
            },
        ),
    ]
