# Generated by Django 4.2.16 on 2026-07-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_smartsendbatch_smartsendrecipientlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartsendbatch',
            name='delay',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='smartsendbatch',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
