# Generated by Django 4.2.16 on 2026-07-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_smartsendbatch_delay_smartsendbatch_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartsendrecipientlog',
            name='open_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smartsendrecipientlog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
