# Generated by Django 4.2.16 on 2026-06-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0002_tenantrole_tenantmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='emailjs_private_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emailjs_public_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emailjs_service_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emailjs_template_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registration_admin_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
