# Generated by Django 4.2.16 on 2026-06-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0003_tenant_emailjs_private_key_tenant_emailjs_public_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_platform_stripe', models.DecimalField(decimal_places=2, default=7, max_digits=5)),
                ('commission_own_stripe', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات المنصة',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_account_holder',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_iban',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_swift',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_mode',
            field=models.CharField(choices=[('platform', 'حساب المدير العام'), ('own', 'حساب الشركة الخاص')], default='platform', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_secret_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
