# Generated by Django 4.2.16 on 2026-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0005_platformsettings_express_payout_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='transfer_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payout_receipts/'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='transfer_reference',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
