# Generated by Django 4.2.16 on 2026-07-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0006_payoutrequest_transfer_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم الباقة')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الشهري')),
                ('currency', models.CharField(default='AED', max_length=10, verbose_name='العملة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف/المزايا')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاحة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'باقة اشتراك',
                'verbose_name_plural': 'باقات الاشتراك',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='بداية الاشتراك')),
                ('end_date', models.DateField(verbose_name='نهاية الاشتراك')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='platform_core.subscriptionplan', verbose_name='الباقة')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='platform_core.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'اشتراك شركة',
                'verbose_name_plural': 'اشتراكات الشركات',
                'ordering': ['end_date'],
            },
        ),
    ]
