# Generated by Django 4.2.16 on 2026-07-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0008_landing_demo_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(blank=True, verbose_name='المزايا (كل ميزة في سطر)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='الأكثر شيوعاً'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='show_on_landing',
            field=models.BooleanField(default=True, verbose_name='عرض في صفحة الهبوط'),
        ),
    ]
