# Generated by Django 4.2.16 on 2026-07-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0009_subscriptionplan_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(blank=True, default='منظومة أعمال متكاملة', max_length=120)),
                ('hero_title', models.CharField(blank=True, default='أدر حملاتك البريدية وفواتيرك من مكان واحد احترافي', max_length=250)),
                ('hero_desc', models.TextField(blank=True, default='inexcsuite تجمع قوة الحملات البريدية الاحترافية مع نظام فواتير ودفع متكامل.')),
                ('features_title', models.CharField(blank=True, default='ركيزتان لنمو أعمالك', max_length=150)),
                ('services_title', models.CharField(blank=True, default='كل ما تحتاجه لإدارة أعمالك', max_length=150)),
                ('pricing_title', models.CharField(blank=True, default='باقات تناسب نموّك', max_length=150)),
                ('pricing_sub', models.CharField(blank=True, default='ابدأ بتجربة مجانية 14 يوماً — بلا التزام', max_length=200)),
                ('pillar1_title', models.CharField(blank=True, default='الحملات البريدية', max_length=120)),
                ('pillar1_desc', models.TextField(blank=True, default='صمّم وأرسل حملات بريدية احترافية تصل لعملائك في الوقت المناسب.')),
                ('pillar2_title', models.CharField(blank=True, default='الفواتير والدفع', max_length=120)),
                ('pillar2_desc', models.TextField(blank=True, default='أنشئ فواتير أنيقة وأرسلها لعملائك واستقبل مدفوعاتك بسلاسة.')),
                ('footer_company', models.CharField(blank=True, default='شركة التميز الابتكاري', max_length=150)),
                ('footer_location', models.CharField(blank=True, default='الإمارات — دبي', max_length=150)),
                ('whatsapp_phone', models.CharField(blank=True, default='971543475500', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محتوى صفحة الهبوط',
                'verbose_name_plural': 'محتوى صفحة الهبوط',
            },
        ),
    ]
