# Generated by Django 4.2.16 on 2026-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0010_landingcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='اسم الشركة')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهرة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شركة معتمِدة',
                'verbose_name_plural': 'الشركات المعتمِدة',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
