# Generated by Django 4.2.16 on 2026-07-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0011_landingclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingclient',
            name='icon',
            field=models.CharField(blank=True, default='bi-building', max_length=60, verbose_name='الأيقونة (Bootstrap Icon)'),
        ),
        migrations.AlterField(
            model_name='landingclient',
            name='name',
            field=models.CharField(max_length=160, verbose_name='الاسم'),
        ),
    ]
