# Generated by Django 4.2.16 on 2026-07-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0012_landingclient_icon_alter_landingclient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingclient',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميّز'),
        ),
    ]
