# Generated by Django 4.2.16 on 2026-07-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0013_landingclient_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='footer_tagline',
            field=models.CharField(blank=True, default='inexcsuite أحد أنظمة شركة التميز الابتكاري', max_length=200),
        ),
    ]
