# Generated by Django 4.2.16 on 2026-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0014_landingcontent_footer_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='privacy_content',
            field=models.TextField(blank=True, verbose_name='محتوى سياسة الخصوصية'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='terms_content',
            field=models.TextField(blank=True, verbose_name='محتوى شروط الاستخدام'),
        ),
    ]
