# Generated by Django 4.2.16 on 2026-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0015_landingcontent_privacy_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_yearly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر السنوي'),
        ),
    ]
