# Generated by Django 4.2.16 on 2026-07-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0016_subscriptionplan_price_yearly'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='parent_logo',
            field=models.ImageField(blank=True, null=True, upload_to='landing/', verbose_name='شعار الشركة الأم'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='show_parent_logo',
            field=models.BooleanField(default=True, verbose_name='عرض شعار الشركة الأم'),
        ),
    ]
