# Generated by Django 4.2.16 on 2026-07-07 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platform_core', '0017_landingcontent_parent_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رمز التحقق بخطوتين',
                'verbose_name_plural': 'رموز التحقق بخطوتين',
            },
        ),
    ]
