# Generated by Django 4.2.16 on 2026-07-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0018_admintotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(default='bi-bell', max_length=40)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
