# Generated by Django 4.2.16 on 2026-07-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0019_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='onboarding_seen',
            field=models.BooleanField(default=False),
        ),
    ]
