# Generated by Django 4.2.16 on 2026-06-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='البريد')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='الشركة/الجهة')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('trn', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['name'],
            },
        ),
    ]
