# Generated by Django 4.2.16 on 2026-06-25 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0004_platformsettings_tenant_bank_account_holder_and_more'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_customers', to='platform_core.tenant'),
        ),
    ]
