# Generated by Django 4.2.16 on 2026-06-28 02:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0006_payoutrequest_transfer_date_and_more'),
        ('accounting', '0002_customer_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='رقم الهوية/الإقامة')),
                ('id_expiry', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الهوية')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='المسمى الوظيفي')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الراتب الأساسي')),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='البدلات')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الخصومات الثابتة')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='رقم الآيبان')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('status', models.CharField(choices=[('active', 'على رأس العمل'), ('terminated', 'منتهي الخدمة')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='platform_core.tenant')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('month', models.IntegerField(verbose_name='الشهر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('paid', 'مدفوع')], default='draft', max_length=20, verbose_name='الحالة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي الرواتب')),
                ('expense_id', models.IntegerField(blank=True, null=True, verbose_name='معرّف المصروف المرتبط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='platform_core.tenant')),
            ],
            options={
                'verbose_name': 'مسير رواتب',
                'verbose_name_plural': 'مسيرات الرواتب',
                'ordering': ['-year', '-month'],
                'unique_together': {('tenant', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الأساسي')),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='البدلات')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الخصومات')),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الصافي')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='accounting.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='accounting.payrollrun')),
            ],
            options={
                'verbose_name': 'قسيمة راتب',
                'verbose_name_plural': 'قسائم الرواتب',
                'ordering': ['employee__full_name'],
            },
        ),
    ]
