# Generated by Django 4.2.16 on 2026-06-18 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
