# Generated by Django 4.2.16 on 2026-06-19 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates_mgr', '0002_emailtemplate_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPaymentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('title', models.CharField(default='معلومات الدفع', max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('iban', models.CharField(blank=True, max_length=80)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('swift', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('amount', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
