# Generated by Django 4.2.16 on 2026-06-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgr', '0003_bankpaymentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='blocks_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
