# Generated by Django 4.2.16 on 2026-06-23 13:20

import apps.registrations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_core', '0002_tenantrole_tenantmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Spark Language Institute', max_length=180)),
                ('header_title', models.CharField(blank=True, default='', max_length=180)),
                ('header_subtitle', models.CharField(blank=True, default='Registration Form - One to One (VIP)', max_length=220)),
                ('logo', models.FileField(blank=True, null=True, upload_to='registration_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('schema', models.JSONField(blank=True, default=apps.registrations.models.default_registration_schema)),
                ('terms_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_form_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_templates', to='platform_core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('student_name', models.CharField(blank=True, default='', max_length=180)),
                ('student_email', models.EmailField(blank=True, default='', max_length=254)),
                ('signature_data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_submissions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='registrations.registrationformtemplate')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_submissions', to='platform_core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
