# Generated by Django 4.2.16 on 2026-06-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsubmission',
            name='admin_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationsubmission',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
