# Generated by Django 4.2.16 on 2026-07-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0020_tenantmembership_onboarding_seen'),
        ('registrations', '0002_registrationsubmission_admin_notified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الموظف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_employees', to='platform_core.tenant')),
            ],
            options={
                'verbose_name': 'موظف متابعة',
                'verbose_name_plural': 'موظفو المتابعة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=40, verbose_name='رقم الجوال')),
                ('status', models.CharField(choices=[('potential', 'عميل محتمل'), ('followup', 'متابعة'), ('deposit', 'دفعة مدفوعة'), ('registered', 'تم التسجيل'), ('client', 'عميل'), ('not_interested', 'غير مهتم')], default='potential', max_length=20, verbose_name='حالة العميل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('reminder_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التذكير')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='registrations.regemployee', verbose_name='اسم الموظف')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_clients', to='platform_core.tenant')),
            ],
            options={
                'verbose_name': 'عميل متابعة',
                'verbose_name_plural': 'عملاء المتابعة',
                'ordering': ['-created_at'],
            },
        ),
    ]
