# Generated by Django 4.2.16 on 2026-07-18 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0003_regemployee_regclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='regclient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_clients_created', to=settings.AUTH_USER_MODEL, verbose_name='أضافه'),
        ),
    ]
