# Generated by Django 4.2.16 on 2026-07-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_regclient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='regclient',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_clients', to='registrations.regemployee', verbose_name='سجّله'),
        ),
    ]
