# Generated by Django 4.2.16 on 2026-06-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(default='شركة التميز الابتكاري لتصميم نظم الحاسب الآلي التعليمية والتدريبية', max_length=300)),
                ('name_en', models.CharField(blank=True, default='ALTMYZ ALABTKARY FOR EDUCATION & TRAINING COMPUTER SOFTWARE CO', max_length=300)),
                ('email', models.EmailField(blank=True, default='info@inexc.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+971543475500', max_length=50)),
                ('website', models.CharField(blank=True, default='www.inexc.com', max_length=120)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('trn', models.CharField(blank=True, default='104863757100001', max_length=50, verbose_name='الرقم الضريبي')),
                ('license_no', models.CharField(blank=True, default='1393230', max_length=50, verbose_name='رقم الرخصة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('invoice_footer', models.TextField(blank=True, default='شكراً لتعاملكم معنا')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
            },
        ),
    ]
