# Generated by Django 4.2.16 on 2026-06-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
    ]
