# Generated by Django 4.2.16 on 2026-06-20 00:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_companysettings_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('due', 'فاتورة مستحقة'), ('sales', 'فاتورة مبيعات')], default='sales', max_length=10)),
                ('invoice_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_address', models.CharField(blank=True, max_length=300)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('cheque', 'شيك'), ('bank', 'تحويل بنكي'), ('card', 'بطاقة / Stripe'), ('other', 'أخرى')], default='cash', max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=120, verbose_name='مرجع الدفع (رقم شيك/تحويل)')),
                ('status', models.CharField(choices=[('unpaid', 'غير مدفوعة'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], default='unpaid', max_length=12)),
                ('currency', models.CharField(default='aed', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='نسبة الضريبة %')),
                ('notes', models.TextField(blank=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير الإلكترونية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.salesinvoice')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
