# Generated by Django 4.2.16 on 2026-06-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_salesinvoice_salesinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='مرفق'),
        ),
    ]
