# Generated by Django 4.2.16 on 2026-06-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0006_payoutrequest_transfer_date_and_more'),
        ('payments', '0006_finance_tenant_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='invoice_branding/', verbose_name='الشعار')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='invoice_branding/', verbose_name='التوقيع')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='invoice_branding/', verbose_name='الختم')),
                ('primary_color', models.CharField(default='#0b4ea2', max_length=9, verbose_name='اللون الرئيسي')),
                ('secondary_color', models.CharField(default='#1565c0', max_length=9, verbose_name='اللون الثانوي')),
                ('text_color', models.CharField(default='#1f2937', max_length=9, verbose_name='لون النص')),
                ('company_name_ar', models.CharField(blank=True, default='', max_length=300, verbose_name='اسم الشركة (عربي)')),
                ('company_name_en', models.CharField(blank=True, default='', max_length=300, verbose_name='اسم الشركة (إنجليزي)')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف')),
                ('website', models.CharField(blank=True, default='', max_length=120, verbose_name='الموقع')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='العنوان')),
                ('trn', models.CharField(blank=True, default='', max_length=50, verbose_name='الرقم الضريبي')),
                ('license_no', models.CharField(blank=True, default='', max_length=50, verbose_name='رقم الرخصة')),
                ('invoice_footer', models.TextField(blank=True, default='شكراً لتعاملكم معنا', verbose_name='تذييل الفاتورة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_branding', to='platform_core.tenant')),
            ],
            options={
                'verbose_name': 'تصميم فاتورة',
                'verbose_name_plural': 'تصاميم الفواتير',
            },
        ),
    ]
