# Generated by Django 4.2.16 on 2026-06-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_invoicebranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='kind',
            field=models.CharField(choices=[('sales', 'فاتورة مبيعات'), ('due', 'فاتورة مستحقة'), ('purchase', 'فاتورة شراء'), ('receipt', 'سند قبض'), ('payment', 'سند صرف'), ('quote', 'عرض سعر')], default='sales', max_length=12),
        ),
    ]
