# Generated by Django 4.2.16 on 2026-06-29 13:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_salesinvoice_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
