# Generated by Django 4.2.16 on 2026-06-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_crmquote_crmquoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmdeal',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد العميل'),
        ),
    ]
