# Generated by Django 4.2.16 on 2026-06-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_crmdeal_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmdeal',
            name='customer_email',
        ),
        migrations.AddField(
            model_name='crmquote',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد العميل'),
        ),
    ]
